### PR TITLE
[WIP] - prettify, fix typos and add links

### PR DESCRIPTION
**Pull request by Remi-Gau**
No ready to merge yet but at least it is a start

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Good to review

**Comment by Remi-Gau** [comment]
Good to review;
Not sure you can see much in terms of rendering before merging: you said that there is no way to render this locally, right?

**Comment by jsheunis** [comment]
There is. You should be able to do this by running

`make html`

from the docs directory in your repo. The rendered files should then be in the docs/_build directory, and viewable in the browser

**Comment by Remi-Gau** [comment]
OK. Some links are not there. Let me fix that.

**Comment by Remi-Gau** [comment]
It should be good now.

**Pull request merged**
